### ISSUE TITLE
Notation "r, a" in Var.v conflicts with Ltac for matching multiple hypotheses

### ISSUE THREAD

**Issue by tz18** [lpw25/shifted-names#1]
Trying to write a tactic such as:
```
Ltac SolveEverything:=
  match reverse goal with 
  | H1: _, H2: _  |- _ => idtac H1
end.
```
Results in `Unknown interpretation for notation "_ , _".` when shifted-names is used.

I've figured out it's due to this notation:
https://github.com/lpw25/shifted-names/blob/eb28b950677605977af56402ae614a825e0a1441/src/Var.v#L897-L898

And these ones also interfere:
https://github.com/lpw25/shifted-names/blob/eb28b950677605977af56402ae614a825e0a1441/src/Var.v#L885-L890

Maybe we could use ",," instead?

**Comment by lpw25** [comment]
I've also hit this problem, and my current working branches have just disabled the syntax for now. Ideally, I'd like to work out how to have a simple clean syntax without interfering with the main grammar, but after a few hours wrestling with coq's notation machinery I gave up.

For now, I would happily accept a PR to change to use `,,`, or perhaps replace `,` with `;` and replace `;` with `;;`.
